"""ajuste financeiro completo

Revision ID: 74da373f8785
Revises: 83b4fe52c677
Create Date: 2026-06-27 19:16:17.606108
"""
from alembic import op
import sqlalchemy as sa


revision = '74da373f8785'
down_revision = '83b4fe52c677'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('financeiro', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('categoria', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('data', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('data_vencimento', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('forma_pagamento', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('paciente_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('profissional_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('agendamento_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('observacoes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('criado_em', sa.DateTime(), nullable=True))

        batch_op.alter_column(
            'descricao',
            existing_type=sa.VARCHAR(length=200),
            nullable=False
        )

        batch_op.alter_column(
            'valor',
            existing_type=sa.FLOAT(),
            nullable=False
        )

        batch_op.create_foreign_key(
            'fk_financeiro_paciente_id',
            'paciente',
            ['paciente_id'],
            ['id']
        )

        batch_op.create_foreign_key(
            'fk_financeiro_agendamento_id',
            'agendamento',
            ['agendamento_id'],
            ['id']
        )

        batch_op.create_foreign_key(
            'fk_financeiro_profissional_id',
            'profissional',
            ['profissional_id'],
            ['id']
        )


def downgrade():
    with op.batch_alter_table('financeiro', schema=None) as batch_op:
        batch_op.drop_constraint('fk_financeiro_profissional_id', type_='foreignkey')
        batch_op.drop_constraint('fk_financeiro_agendamento_id', type_='foreignkey')
        batch_op.drop_constraint('fk_financeiro_paciente_id', type_='foreignkey')

        batch_op.drop_column('criado_em')
        batch_op.drop_column('observacoes')
        batch_op.drop_column('agendamento_id')
        batch_op.drop_column('profissional_id')
        batch_op.drop_column('paciente_id')
        batch_op.drop_column('status')
        batch_op.drop_column('forma_pagamento')
        batch_op.drop_column('data_vencimento')
        batch_op.drop_column('data')
        batch_op.drop_column('categoria')
        batch_op.drop_column('tipo')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('financeiro', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('valor',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('descricao',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.drop_column('criado_em')
        batch_op.drop_column('observacoes')
        batch_op.drop_column('agendamento_id')
        batch_op.drop_column('profissional_id')
        batch_op.drop_column('paciente_id')
        batch_op.drop_column('status')
        batch_op.drop_column('forma_pagamento')
        batch_op.drop_column('data_vencimento')
        batch_op.drop_column('data')
        batch_op.drop_column('categoria')
        batch_op.drop_column('tipo')

    # ### end Alembic commands ###
