"""campos cliente agendamento

Revision ID: 83b4fe52c677
Revises: e57404cc2326
Create Date: 2026-06-27 18:34:19.406534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83b4fe52c677'
down_revision = 'e57404cc2326'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agendamento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cliente_nome', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('cliente_telefone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('cliente_email', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('cliente_cpf', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('cliente_data_nascimento', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('observacoes_paciente', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('observacoes_consulta', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agendamento', schema=None) as batch_op:
        batch_op.drop_column('observacoes_consulta')
        batch_op.drop_column('observacoes_paciente')
        batch_op.drop_column('cliente_data_nascimento')
        batch_op.drop_column('cliente_cpf')
        batch_op.drop_column('cliente_email')
        batch_op.drop_column('cliente_telefone')
        batch_op.drop_column('cliente_nome')

    # ### end Alembic commands ###
