"""add campos paciente

Revision ID: e57404cc2326
Revises: 6ba53e4e9e62
Create Date: 2026-06-27 18:12:39.720542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e57404cc2326'
down_revision = '6ba53e4e9e62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paciente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cpf', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('convenio', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('plano', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('observacoes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paciente', schema=None) as batch_op:
        batch_op.drop_column('observacoes')
        batch_op.drop_column('plano')
        batch_op.drop_column('convenio')
        batch_op.drop_column('cpf')

    # ### end Alembic commands ###
